# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shopping_platform_pb2 as shopping__platform__pb2


class MarketServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSeller = channel.unary_unary(
                '/shoppingplatform.MarketService/RegisterSeller',
                request_serializer=shopping__platform__pb2.RegisterSellerRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.Response.FromString,
                )
        self.SellItem = channel.unary_unary(
                '/shoppingplatform.MarketService/SellItem',
                request_serializer=shopping__platform__pb2.SellerItemOperationRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.Response.FromString,
                )
        self.UpdateItem = channel.unary_unary(
                '/shoppingplatform.MarketService/UpdateItem',
                request_serializer=shopping__platform__pb2.SellerItemOperationRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.Response.FromString,
                )
        self.DeleteItem = channel.unary_unary(
                '/shoppingplatform.MarketService/DeleteItem',
                request_serializer=shopping__platform__pb2.SellerItemOperationRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.Response.FromString,
                )
        self.DisplaySellerItems = channel.unary_stream(
                '/shoppingplatform.MarketService/DisplaySellerItems',
                request_serializer=shopping__platform__pb2.DisplayItemsRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.Item.FromString,
                )
        self.RegisterBuyer = channel.unary_unary(
                '/shoppingplatform.MarketService/RegisterBuyer',
                request_serializer=shopping__platform__pb2.RegisterBuyerRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.Response.FromString,
                )
        self.SearchItem = channel.unary_stream(
                '/shoppingplatform.MarketService/SearchItem',
                request_serializer=shopping__platform__pb2.SearchItemRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.Item.FromString,
                )
        self.BuyItem = channel.unary_unary(
                '/shoppingplatform.MarketService/BuyItem',
                request_serializer=shopping__platform__pb2.BuyItemRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.Response.FromString,
                )
        self.AddToWishlist = channel.unary_unary(
                '/shoppingplatform.MarketService/AddToWishlist',
                request_serializer=shopping__platform__pb2.WishlistRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.Response.FromString,
                )
        self.RateItem = channel.unary_unary(
                '/shoppingplatform.MarketService/RateItem',
                request_serializer=shopping__platform__pb2.RateItemRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.Response.FromString,
                )
        self.NotifyClient = channel.unary_unary(
                '/shoppingplatform.MarketService/NotifyClient',
                request_serializer=shopping__platform__pb2.NotifyClientRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.Response.FromString,
                )


class MarketServiceServicer(object):
    """Service definition
    """

    def RegisterSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplaySellerItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToWishlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSeller,
                    request_deserializer=shopping__platform__pb2.RegisterSellerRequest.FromString,
                    response_serializer=shopping__platform__pb2.Response.SerializeToString,
            ),
            'SellItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SellItem,
                    request_deserializer=shopping__platform__pb2.SellerItemOperationRequest.FromString,
                    response_serializer=shopping__platform__pb2.Response.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=shopping__platform__pb2.SellerItemOperationRequest.FromString,
                    response_serializer=shopping__platform__pb2.Response.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=shopping__platform__pb2.SellerItemOperationRequest.FromString,
                    response_serializer=shopping__platform__pb2.Response.SerializeToString,
            ),
            'DisplaySellerItems': grpc.unary_stream_rpc_method_handler(
                    servicer.DisplaySellerItems,
                    request_deserializer=shopping__platform__pb2.DisplayItemsRequest.FromString,
                    response_serializer=shopping__platform__pb2.Item.SerializeToString,
            ),
            'RegisterBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterBuyer,
                    request_deserializer=shopping__platform__pb2.RegisterBuyerRequest.FromString,
                    response_serializer=shopping__platform__pb2.Response.SerializeToString,
            ),
            'SearchItem': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchItem,
                    request_deserializer=shopping__platform__pb2.SearchItemRequest.FromString,
                    response_serializer=shopping__platform__pb2.Item.SerializeToString,
            ),
            'BuyItem': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyItem,
                    request_deserializer=shopping__platform__pb2.BuyItemRequest.FromString,
                    response_serializer=shopping__platform__pb2.Response.SerializeToString,
            ),
            'AddToWishlist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToWishlist,
                    request_deserializer=shopping__platform__pb2.WishlistRequest.FromString,
                    response_serializer=shopping__platform__pb2.Response.SerializeToString,
            ),
            'RateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RateItem,
                    request_deserializer=shopping__platform__pb2.RateItemRequest.FromString,
                    response_serializer=shopping__platform__pb2.Response.SerializeToString,
            ),
            'NotifyClient': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyClient,
                    request_deserializer=shopping__platform__pb2.NotifyClientRequest.FromString,
                    response_serializer=shopping__platform__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shoppingplatform.MarketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketService(object):
    """Service definition
    """

    @staticmethod
    def RegisterSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppingplatform.MarketService/RegisterSeller',
            shopping__platform__pb2.RegisterSellerRequest.SerializeToString,
            shopping__platform__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SellItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppingplatform.MarketService/SellItem',
            shopping__platform__pb2.SellerItemOperationRequest.SerializeToString,
            shopping__platform__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppingplatform.MarketService/UpdateItem',
            shopping__platform__pb2.SellerItemOperationRequest.SerializeToString,
            shopping__platform__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppingplatform.MarketService/DeleteItem',
            shopping__platform__pb2.SellerItemOperationRequest.SerializeToString,
            shopping__platform__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisplaySellerItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/shoppingplatform.MarketService/DisplaySellerItems',
            shopping__platform__pb2.DisplayItemsRequest.SerializeToString,
            shopping__platform__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppingplatform.MarketService/RegisterBuyer',
            shopping__platform__pb2.RegisterBuyerRequest.SerializeToString,
            shopping__platform__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/shoppingplatform.MarketService/SearchItem',
            shopping__platform__pb2.SearchItemRequest.SerializeToString,
            shopping__platform__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuyItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppingplatform.MarketService/BuyItem',
            shopping__platform__pb2.BuyItemRequest.SerializeToString,
            shopping__platform__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToWishlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppingplatform.MarketService/AddToWishlist',
            shopping__platform__pb2.WishlistRequest.SerializeToString,
            shopping__platform__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppingplatform.MarketService/RateItem',
            shopping__platform__pb2.RateItemRequest.SerializeToString,
            shopping__platform__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shoppingplatform.MarketService/NotifyClient',
            shopping__platform__pb2.NotifyClientRequest.SerializeToString,
            shopping__platform__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
