# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: correct_raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63orrect_raft.proto\"+\n\rKeyValMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"!\n\x0eSuccessMessage\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nKeyMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"3\n\x11SuccessValMessage\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"_\n\x14RequestTermIdMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"5\n\x06Update\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\".\n\x05\x45ntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x17\n\x06update\x18\x02 \x01(\x0b\x32\x07.Update\"\x8e\x01\n\x13\x41ppendTermIdMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x17\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x06.Entry\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"1\n\x11TermResultMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\x08\"\x1f\n\rPeriodMessage\x12\x0e\n\x06period\x18\x01 \x01(\x05\"\x0e\n\x0c\x45mptyMessage\"0\n\rLeaderMessage\x12\x0e\n\x06leader\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2\xd5\x02\n\x07Service\x12\x38\n\x0bRequestVote\x12\x15.RequestTermIdMessage\x1a\x12.TermResultMessage\x12\x39\n\rAppendEntries\x12\x14.AppendTermIdMessage\x1a\x12.TermResultMessage\x12(\n\x07Suspend\x12\x0e.PeriodMessage\x1a\r.EmptyMessage\x12*\n\tGetLeader\x12\r.EmptyMessage\x1a\x0e.LeaderMessage\x12)\n\x06SetVal\x12\x0e.KeyValMessage\x1a\x0f.SuccessMessage\x12)\n\x06GetVal\x12\x0b.KeyMessage\x1a\x12.SuccessValMessage\x12)\n\tGetStatus\x12\r.EmptyMessage\x1a\r.EmptyMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'correct_raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KEYVALMESSAGE']._serialized_start=22
  _globals['_KEYVALMESSAGE']._serialized_end=65
  _globals['_SUCCESSMESSAGE']._serialized_start=67
  _globals['_SUCCESSMESSAGE']._serialized_end=100
  _globals['_KEYMESSAGE']._serialized_start=102
  _globals['_KEYMESSAGE']._serialized_end=127
  _globals['_SUCCESSVALMESSAGE']._serialized_start=129
  _globals['_SUCCESSVALMESSAGE']._serialized_end=180
  _globals['_REQUESTTERMIDMESSAGE']._serialized_start=182
  _globals['_REQUESTTERMIDMESSAGE']._serialized_end=277
  _globals['_UPDATE']._serialized_start=279
  _globals['_UPDATE']._serialized_end=332
  _globals['_ENTRY']._serialized_start=334
  _globals['_ENTRY']._serialized_end=380
  _globals['_APPENDTERMIDMESSAGE']._serialized_start=383
  _globals['_APPENDTERMIDMESSAGE']._serialized_end=525
  _globals['_TERMRESULTMESSAGE']._serialized_start=527
  _globals['_TERMRESULTMESSAGE']._serialized_end=576
  _globals['_PERIODMESSAGE']._serialized_start=578
  _globals['_PERIODMESSAGE']._serialized_end=609
  _globals['_EMPTYMESSAGE']._serialized_start=611
  _globals['_EMPTYMESSAGE']._serialized_end=625
  _globals['_LEADERMESSAGE']._serialized_start=627
  _globals['_LEADERMESSAGE']._serialized_end=675
  _globals['_SERVICE']._serialized_start=678
  _globals['_SERVICE']._serialized_end=1019
# @@protoc_insertion_point(module_scope)
